[GLOBAL]
pants_version = "2.29.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.shell",
    "pants.backend.experimental.tools.yamllint"
]

[anonymous-telemetry]
enabled = false

[system-binaries]
system_binary_paths = [
  "/usr/bin",
  "/bin",
  "/usr/local/bin",
  "/opt/homebrew/bin",
  "/home/*/.nvm/versions/node/*/bin",
  "/Users/*/.nvm/versions/node/*/bin",
]

[cli.alias]
all = "::"
lock = "generate-lockfiles"
venv = "export --py-resolve-format=symlinked_immutable_virtualenv --resolve=python-default"

[source]
root_patterns = [
  "/",
]

[python]
interpreter_constraints = [">=3.12"]
enable_resolves = true

[test]
use_coverage = true

[pytest]
install_from_resolve = "python-default"

[ruff]
version = "0.11.5"
